### PR TITLE
#9 Add support for phpunit 7

### PR DESCRIPTION
**Pull request by funivan**

### CODE REVIEW

**Comment by Bilge** [comment]
If the build is failing it's not getting merged.

**Comment by funivan** [comment]
Yep. Correct. I will investigate it tomorrow.

**Comment by funivan** [comment]
@Bilge I tried to safely support phpunit 7 but can not figure out how to do this.
Maybe it would be better to create new version with the support of phpunit7 and drop support for 5 and 6 ?

**Comment by Bilge** [comment]
There will be one repository to eliminate code duplication. I'm sure you'll figure it out if you put your mind to it.

**Comment by funivan** [comment]
Cant fix it. Don`t know how to do it properly.

**Pull request closed without merging**
